/**
 * Bundle the browser client (client/session.mjs + yjs + y-partyserver's
 * provider) into ONE ES module the editor can `import()` beside itself:
 *
 *   docsync/editor/collab-client.js
 *
 * That file is committed. It lives under docsync/ so it vendors to every
 * consumer repo like the rest of the engine, and docsync.stage copies it next
 * to edit.html — the editor is a single file with no build step, and this is
 * the one dependency it cannot load from a CDN as-is (y-partyserver's provider
 * is only published as a bare-specifier ESM graph).
 *
 *   cd collab && npm run build:client
 *
 * Re-run after touching client/session.mjs or ../serialize.mjs. The Node
 * tests import the source, not the bundle, so a stale bundle is caught by the
 * Playwright spec (tests/editor/collab.spec.js), not by `npm test` here.
 */
import { build } from 'esbuild';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'docsync', 'editor', 'collab-client.js');

await build({
  entryPoints: [join(HERE, 'client', 'session.mjs')],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['es2022'],
  minify: true,
  sourcemap: false,
  legalComments: 'none',
  outfile: OUT,
  banner: {
    js: '// GENERATED by collab/build-client.mjs — do not edit. Source: collab/client/session.mjs\n'
      + '// Yjs (MIT, Kevin Jahns) + y-partyserver provider (ISC, Cloudflare) + lib0 (MIT).',
  },
});
console.log('wrote', OUT);
